//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PmTool.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class DcScopes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DcScopes()
        {
            this.DataCenters = new HashSet<DataCenters>();
        }
    
        public int Dc_scope_id { get; set; }
        public string Dc_scope_name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DataCenters> DataCenters { get; set; }
    }
}
