//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PmTool.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class OtherProjects
    {
        public int Other_request_id { get; set; }
        public Nullable<bool> Status { get; set; }
        public string Project_description { get; set; }
        public Nullable<int> Other_requestor_id { get; set; }
        public Nullable<int> Other_projectType { get; set; }
        public Nullable<int> Assigned_pm { get; set; }
    
        public virtual ProjectTypes ProjectTypes { get; set; }
        public virtual Users Users { get; set; }
        public virtual ProjectNames ProjectNames { get; set; }
    }
}
