//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PmTool.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class PmProjectCost
    {
        public int Project_id { get; set; }
        public string Project_name { get; set; }
        public Nullable<double> Local_area_network_systems { get; set; }
        public Nullable<double> Wide_area_network { get; set; }
        public Nullable<double> Wireless_Lan_Infrastructure_equipment { get; set; }
        public Nullable<double> Indetification_for_com_systems { get; set; }
        public Nullable<double> Com_grounding { get; set; }
        public Nullable<double> Cable_Trays { get; set; }
        public Nullable<double> Handholes_and_manholes { get; set; }
        public Nullable<double> Com_cabinets { get; set; }
        public Nullable<double> Racks { get; set; }
        public Nullable<double> Frames { get; set; }
        public Nullable<double> Enclosures { get; set; }
        public Nullable<double> Campus_distribution_subsystems { get; set; }
        public Nullable<double> Vertical_distribution_subsystem { get; set; }
        public Nullable<double> Com_horizontal_cabling { get; set; }
        public Nullable<double> Com_circuits { get; set; }
        public Nullable<double> Com_patch_cords { get; set; }
        public Nullable<double> Station_cords { get; set; }
        public Nullable<double> Cross_connect_wires { get; set; }
        public Nullable<double> Multimedia_equipment { get; set; }
        public Nullable<double> PBX_switch_processor { get; set; }
        public Nullable<double> Expansion_phone_network { get; set; }
        public Nullable<double> Desk_phones { get; set; }
        public Nullable<double> Public_wall_phones { get; set; }
        public Nullable<double> Conferencing_phones { get; set; }
        public Nullable<double> Internal_celular { get; set; }
        public Nullable<double> Printers { get; set; }
        public Nullable<double> Training_pcs { get; set; }
        public Nullable<double> Servers { get; set; }
        public Nullable<double> Servers_racks { get; set; }
        public Nullable<double> A_E_desing_consultants { get; set; }
        public Nullable<double> QC_Consultants { get; set; }
        public Nullable<double> Project_management_coordination { get; set; }
        public Nullable<double> Temporary_communications { get; set; }
        public Nullable<double> Telecom_cabling_demoliton { get; set; }
        public Nullable<double> Other_expenses { get; set; }
    }
}
